# first mission summary

- here we are applying the numpy fumndamentals on NYC airport taxi dataset
- here is the dataset columns

- pickup_month:  The month of the trip (January is 1, December is 12).
- pickup_day:  The day of the month of the trip.
- pickup_location_code:  The airport or borough where the trip started.
- dropoff_location_code: The airport or borough where the trip finished.
- trip_distance: The distance of the trip in miles.
- trip_length: The length of the trip in seconds.
- fare_amount: The base fare of the trip, in dollars.
- total_amount: The total amount charged to the passenger, including all fees, tolls and tips. 


In [2]:
import numpy as np
import csv
#opening the nyc csv file
opened_file = open("nyc_taxis.csv")
data = list(csv.reader(opened_file))
headers = data[0] #removing headers
data = data[1:]
print(headers , "\n" , data[0])

['pickup_year', 'pickup_month', 'pickup_day', 'pickup_dayofweek', 'pickup_time', 'pickup_location_code', 'dropoff_location_code', 'trip_distance', 'trip_length', 'fare_amount', 'fees_amount', 'tolls_amount', 'tip_amount', 'total_amount', 'payment_type'] 
 ['2016', '1', '1', '5', '0', '2', '4', '21.00', '2037', '52.00', '0.80', '5.54', '11.65', '69.99', '1']


In [3]:
# convert the dataset items into float to deal with it
taxi_list = []
for row in data:
    rows = []
    for r in row:
        r = float(r)
        rows.append(r)
    taxi_list.append(rows)
print(taxi_list[0])

[2016.0, 1.0, 1.0, 5.0, 0.0, 2.0, 4.0, 21.0, 2037.0, 52.0, 0.8, 5.54, 11.65, 69.99, 1.0]


In [4]:
#convert the data into 2D ndarray using numpy
taxi = np.array(taxi_list)
print(taxi[1])

[2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 1.000e+00
 1.629e+01 1.520e+03 4.500e+01 1.300e+00 0.000e+00 8.000e+00 5.430e+01
 1.000e+00]


- apply the slicing techniques here

In [5]:
print(type(taxi))

<class 'numpy.ndarray'>


In [6]:
print(taxi.ndim)

2


In [7]:
print(taxi.shape)

(89560, 15)


In [8]:
print(taxi.dtype)

float64


In [9]:
print(taxi[500:505 , 1:6])

[[1. 2. 6. 2. 3.]
 [1. 2. 6. 2. 3.]
 [1. 2. 6. 3. 3.]
 [1. 2. 6. 3. 4.]
 [1. 2. 6. 3. 3.]]


In [10]:
# some days in the month
print(taxi[:5 , 2] , taxi[80000:80005 , 1])

[1. 1. 1. 1. 1.] [6. 6. 6. 6. 6.]


In [11]:
#pick up year
print(taxi[[-1, 25124 , 500] , 0])

[2016. 2016. 2016.]


In [12]:
# minimum values for columns
print(taxi.min(axis = 0))

[ 2.016e+03  1.000e+00  1.000e+00  1.000e+00  0.000e+00  0.000e+00
  0.000e+00  0.000e+00  1.000e+00 -5.200e+01 -1.800e+00 -5.540e+00
  0.000e+00 -5.834e+01  1.000e+00]


In [13]:
# maximum values for some rows
print(taxi[:20].max(axis = 1))

[2037. 2016. 2016. 2016. 2016. 2016. 2016. 2016. 2562. 2016. 2016. 2016.
 2016. 2016. 2016. 2016. 2016. 2304. 2016. 2016.]


In [14]:
# maximum value in the matrix
print(taxi.max())

86383.0


In [15]:
# length of our dataset
print(len(taxi) , taxi.shape)

89560 (89560, 15)


In [16]:
taxi[550:560 , 6]

array([6., 4., 2., 3., 2., 4., 4., 4., 1., 6.])

In [17]:
# 2 columns multiplication in our dataset
pickup_month = taxi[:, 1]
pickup_day = taxi[:, 2]
product = pickup_month * pickup_day 
print(product)

[  1.   1.   1. ... 180. 180. 180.]


In [18]:
print(taxi[:, 9].max())
print(taxi[:, 8].max() / 3600 , "hours") # converting the value to hours

400.0
23.995277777777776 hours


In [19]:
trip_distance = taxi[:,7] #distance in miles
trip_length = taxi[:,8] #length in seconds

In [20]:
#calculate the miles per hour for each trip
#convert length from seconds to hours
length_hours = trip_length / 3600
miles_per_hour = trip_distance / length_hours
print(miles_per_hour)
print(miles_per_hour.max()) #somthing wrong here cause it is faster than the fastest plane in the world

[37.11340206 38.58157895 31.27222982 ... 22.29907867 42.41551247
 36.90473407]
82800.0


In [21]:
print(miles_per_hour.mean())
print(miles_per_hour.min())

32.24258580925573
0.0


- difference between functions and methods for numpy specially
- function is stand alone building block which takes input to return output
- method is related to specific object we use it with that object

In [22]:
#functions
print(np.min(miles_per_hour))
print(np.max(miles_per_hour))
print(np.mean(miles_per_hour))

0.0
82800.0
32.24258580925573


In [23]:
#methods
print(miles_per_hour.mean())
print(miles_per_hour.max())

32.24258580925573
82800.0


In [24]:
#. Calculating Statistics For 2D ndarrays

#check the values of the columns [9:13] sum[9:12] should be equal to col[13]
total_amount = taxi[:10,13]
sum_amounts = taxi[:10 , 9:13].sum(axis = 1)
print(total_amount)
print(sum_amounts)

[ 69.99  54.3   37.8   32.76  18.8  105.6   32.25  22.8  131.38  37.3 ]
[ 69.99  54.3   37.8   32.76  18.8  105.6   32.25  22.8  131.38  37.3 ]


In [25]:
c= np.arange(6)
c

array([0, 1, 2, 3, 4, 5])

# try

In [97]:
# create a boolean array for trips with average
# speeds greater than 20,000 mph

mph = taxi[:, 7] / (taxi[:, 8] / 3600)

trips_over_2000_speed = taxi[mph > 20000 , 5:9]
trips_over_2000_speed.shape

taxi[2: 200 , 2:6]

x = np.array(np.zeros((3,3), int))
x[x ==0] = 1
x[1,1] = 2
x[2, 2]= 10
x[0,2]  = 12
x[1,0] = 6
x[0] = 10
x[:,2] = (x[:, 2].sum()) /3
x

array([[10, 10,  7],
       [ 6,  2,  7],
       [ 1,  1,  7]])

In [119]:
taxi_copy = taxi.copy()

taxi_copy[:, 1] = 16
taxi_copy[:,1]

(taxi_copy[:, 5][taxi_copy[:, 5] == 0]) = 1

avg_5_mean = taxi[:, 5].mean()

taxi_copy[:, 5][taxi_copy[:,5] == 1] = avg_5_mean

taxi_copy[:, 5][taxi_copy[:,5] == avg_5_mean].shape

(432,)

In [128]:
jfk = taxi_copy[taxi_copy[:, 6] == 2]
print("number of trips for jfk airport is %d "% jfk.shape[0])

laguardia = taxi_copy[taxi[:, 6] == 3]
print("no of trips for laguardia airport is {}".format(laguardia.shape[0]))


newyork_airport_trips = taxi_copy[taxi_copy[:,6] == 5]
print("no newyork airport trips %d " % newyork_airport_trips.shape[0])

number of trips for jfk airport is 11832 
no of trips for laguardia airport is 16602
no newyork airport trips 63 


In [146]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np .array([[1,2], [3,5]])

np.concatenate((a,b), axis = 1)

array([[1, 2, 3, 1, 2],
       [4, 5, 6, 3, 5]])