## practise mission 2 and boolean indexing with boolean arrays

In [1]:
# opening dataset using numpy 
import numpy as np
taxi = np.genfromtxt("nyc_taxis.csv" , delimiter = "," , skip_header = 1)
taxi[0]

array([2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
       4.000e+00, 2.100e+01, 2.037e+03, 5.200e+01, 8.000e-01, 5.540e+00,
       1.165e+01, 6.999e+01, 1.000e+00])

In [2]:
# understand boolean array 
a = np.array([1,2,3,4])
print(a > 2) # boolean array
print(a[a>2])

[False False  True  True]
[3 4]


In [1]:
taxi[:, 1][taxi[:, 1] == 1]

NameError: name 'taxi' is not defined

In [3]:
# syntax--> array[boolean array]
# for the months in our data 
#jan
pick_month = taxi[:,1]
january = pick_month[pick_month == 1]
print(january)
# february 
feb = pick_month[pick_month == 2]
print(feb)

[1. 1. 1. ... 1. 1. 1.]
[2. 2. 2. ... 2. 2. 2.]


In [4]:
# let's understand for 2D ndarray
a = np.array([[1,2,3,5] , [4,5,6,5] , [7,8,9,2] , [4,5,6,1]])
print(a)
bool_array = [True , False ,True , True]
a[bool_array]

[[1 2 3 5]
 [4 5 6 5]
 [7 8 9 2]
 [4 5 6 1]]


array([[1, 2, 3, 5],
       [7, 8, 9, 2],
       [4, 5, 6, 1]])

In [5]:
# top tips for the tips column
tips = taxi[:,12]
top_tips = tips[tips > 50]
print(top_tips)

[ 52.8   60.    59.34  80.    70.    60.    55.    65.    80.    62.
 100.    58.    62.    75.7   60.    70.  ]


In [6]:
fare_amount = taxi[:,9]
top_fares = fare_amount[fare_amount > 100]
print(top_fares)

[109.5 122.  117.  112.  114.5 102.  105.5 110.5 110.5 101.5 128.  134.5
 102.5 113.  102.5 116.  110.5 119.5 106.5 110.  105.5 113.  115.5 106.5
 120.  121.  100.5 130.  123.  110.5 106.5 400.  116.5 125.  157.5 103.
 120.5 104.  101.  101.  101.  115.5 129.5 112.  106.  114.5 107.  119.
 126.  115.  123.  111.  110.  102.5 110.  126.  112.5 101.5 220.  108.
 150.  101.  134.  101.  113.  180.5 104.  129.  107.5 120.  112.  117.5
 114.5 116.  117.5 116.5 113.5]


In [7]:
# top total highest fees
t = taxi[:,13]
top = t[t>200]
print(top)

[400.3  453.34 220.3  834.84 286.84]


In [8]:
# assigning values using boolean indexing
x = np.zeros((3,3))
x[0 , 1] = 1
x[:,2] = [1,2,3]
x[2,1] = 10
x[1,0] = 5
x[0,0] =4
x

array([[ 4.,  1.,  1.],
       [ 5.,  0.,  2.],
       [ 0., 10.,  3.]])

In [9]:
bool_1 = [True , False ,True]
x[x==5] = 10
x

array([[ 4.,  1.,  1.],
       [10.,  0.,  2.],
       [ 0., 10.,  3.]])

In [10]:
#copy your dataset
taxi_copy = taxi.copy()
total_amount = taxi_copy[:,13]
total_amount[total_amount < 0] = 0
total_amount

array([69.99, 54.3 , 37.8 , ..., 63.34, 44.75, 54.84])

In [11]:
x = np.ones((4,4))
x[0] = 5
x

array([[5., 5., 5., 5.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
x[x<5] = 4
x

array([[5., 5., 5., 5.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [13]:
# syntax for assigning using boolean indexing
#bool = array[:, column_for_comparison] == value_for_comparison
#array[bool, column_for_assignment] = new_value
#all in one line
# array[array[:, column_for_comparison] == value_for_comparison, column_for_assignment] = new_value

In [14]:
bool2 = taxi_copy[:,13] >99
taxi_copy[bool2 , 12] = 10

In [15]:
#create new column 
ones = np.ones((1,taxi_copy.shape[1]))
taxi_copy = np.concatenate((taxi_copy , ones) , axis = 0)


In [16]:
# create a new column filled with `0`.
zeros = np.zeros([taxi.shape[0],1])
modified_taxi = np.concatenate([taxi , zeros ], axis=1)
print(modified_taxi)

[[2.016e+03 1.000e+00 1.000e+00 ... 6.999e+01 1.000e+00 0.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 5.430e+01 1.000e+00 0.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 3.780e+01 2.000e+00 0.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 6.334e+01 1.000e+00 0.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 4.475e+01 1.000e+00 0.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 5.484e+01 2.000e+00 0.000e+00]]
