## Numpy tutorial

**creating numpy array**

In [2]:
# import numpy library 
import numpy as np

# create rank 1 array 
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [4]:
# create rank2 array
arr2 = np.array([[1,2,3],
                [4,5,6]])

print("Array of rank 2: \n",arr2)

Array of rank 2: 
 [[1 2 3]
 [4 5 6]]


In [5]:
# array created using tuple
arr = np.array((1,2,3))
print("array created used passed tuple \n", arr)

array created used passed tuple 
 [1 2 3]


**Accessing the array Index**

In [17]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

print("initial array\n", arr)

sliced_arr = arr[:2 , [0,2]]
print("\nSliced array for first 2 rows and cloumns[0,2]\n", sliced_arr)


# printing elements at specific indices
index_arr = arr[[1 ,2],
                [0 , 2]]
print("\nelements for indices (1,0), (2,2)\n",index_arr)

initial array
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]

Sliced array for first 2 rows and cloumns[0,2]
 [[-1.  0.]
 [ 4.  6.]]

elements for indices (1,0), (2,2)
 [4. 7.]


**basic array operations**

In [19]:
a = np.array([[1,2],[3,4]])

b = np.array([[5,6], [7,8]])

# adding 1 to every element
print("adding 1 to each element in a\n", a + 1)
print("\n subtract 2 from each element in b\n", b - 2)

# sum of all elements
print("\n sum of a is {}".format(a.sum()))
print("\n sum of b is {}".format(b.sum()))

# addind 2 arrays 
print( "\nsum of a and b:\n", a + b)

adding 1 to each element in a
 [[2 3]
 [4 5]]

 subtract 2 from each element in b
 [[3 4]
 [5 6]]

 sum of a is 10

 sum of b is 26

sum of a and b:
 [[ 6  8]
 [10 12]]


**numpy datatype**

In [30]:
a = np.array([1,2,3,4])
# int datatype gussed by numpy 
print("a dtype is", a.dtype)

#float dtype
b = np.array([1.2, 3, 4, 5])
print("\n b dtype is", b.dtype)

#forced datatype
c = np.array([1,2, 3.4, 5.6], dtype = int)
print("\n c dtype is", c.dtype)

d = np.array([1, 2.5, 4], dtype = np.int64)
print("\n d dtype is", d.dtype)

a dtype is int32

 b dtype is float64

 c dtype is int32

 d dtype is int64


**math operations**

In [36]:
a = np.array([[1,2,3], [4,10,2]], dtype = np.int64)
b = np.array([[1.2, 5, 7.3], [10, 5, 6]], dtype = np.int64)

# add two arrays
print("Addition\n" , a + b)

print("\n summtion of an array \n", np.sum(a))

print("square root of each element in array:\n", np.sqrt(b))

print("\ntranspose of array\n", a.T) # T for transpose

Addition
 [[ 2  7 10]
 [14 15  8]]

 summtion of an array 
 22
square root of each element in array:
 [[1.         2.23606798 2.64575131]
 [3.16227766 2.23606798 2.44948974]]

transpose of array
 [[ 1  4]
 [ 2 10]
 [ 3  2]]


**Numpy ndarray**

In [45]:
# create ndarray
a = np.array([[1,2,3], [4,10,5], [6,7,8]])

print("the type of array:" , type(a))
print("\n the dimensions of the array:", a.ndim)
print("\n the shape of the array is", a.shape)
print("\n the size of the array:", a.size)
print("\n the element's size :", a.itemsize)
print("\n the array stores elements in dtype:" , a.dtype)

the type of array: <class 'numpy.ndarray'>

 the dimensions of the array: 2

 the shape of the array is (3, 3)

 the size of the array: 9

 the element's size : 4

 the array stores elements in dtype: int32


**lets try different methods to create arrays**

In [57]:
# np.arange()
a = np.arange(1, 9,2)
print(a)

a = np.zeros((2,3))
print("\na =\n ", a)

[1 3 5 7]

a =
  [[0. 0. 0.]
 [0. 0. 0.]]


In [58]:
# constatnt value array
a = np.full((3,3), 6, dtype= np.int64)
print(a)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


**Unary operators**

In [71]:
arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])

print("largest element in the array is: ", np.max(arr))
print("min number in the rray is: ", arr.min())

print("\n mininmum element for each column: ", arr.min(axis = 0))

print("\nminimum for each row: ", arr.min(axis =1))

largest element in the array is:  9
min number in the rray is:  1

 mininmum element for each column:  [1 1 2]

minimum for each row:  [1 2 1]


In [73]:
# matrix multiplication for 2 arrays
a = np.array([[1,2], 
              [3,4]])

b = np.array([[5,6],
              [0,2]])

print("Matrix multiplication :\n" , a.dot(b))


dot product for these matriecs is :
 [[ 5 10]
 [15 26]]


In [98]:
a = np.array([[1,2,3], 
              [4,10,15],
              [15, 20, 23],
             [10,-2, 3]])

filter = a > 0
a[a[filter], :2]

IndexError: index 4 is out of bounds for axis 0 with size 4