#### Introduction to NumPy: Takeaways
- introduction to numpy library and its methods

In [7]:
# importing numpy
import numpy as np 

#convert list to array
arr = np.array([1 , 2 , 3 , 4])
print(arr)
print(arr.ndim)

[1 2 3 4]
1


the result of is 1D array [1 2 3 4]

In [8]:
#create 2D ndarray
my_list = [[1,1,1,1] , [1,2,3,4] , [4,5,6,7] , [7,8,9,1],[4,5,6,7] , [7,8,9,1]]
arr2 = np.array(my_list)
print(arr2)

[[1 1 1 1]
 [1 2 3 4]
 [4 5 6 7]
 [7 8 9 1]
 [4 5 6 7]
 [7 8 9 1]]


In [9]:
print("numper of rows and columns is: ", arr2.shape) 
print("size of each item in the array is: " , arr2.itemsize)
print("the dimension of the array is: " , arr2.ndim , " ndarray")
np.size(arr2) * arr2.itemsize

numper of rows and columns is:  (6, 4)
size of each item in the array is:  4
the dimension of the array is:  2  ndarray


96

In [10]:
#reshape the array
arr2_newshape = arr2.reshape(4 ,6) 
print(arr2_newshape)
print(arr2.dtype) #elements data type

[[1 1 1 1 1 2]
 [3 4 4 5 6 7]
 [7 8 9 1 4 5]
 [6 7 7 8 9 1]]
int32


In [11]:
print(arr2)

[[1 1 1 1]
 [1 2 3 4]
 [4 5 6 7]
 [7 8 9 1]
 [4 5 6 7]
 [7 8 9 1]]


In [12]:
#slicing for this small array
row_2 = arr2[1]
print(row_2)
row_3 = arr2[3]
print(row_3 , "\n")
# some row together
row1_3 = arr2[1:4]
print(row1_3)

[1 2 3 4]
[7 8 9 1] 

[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 1]]


In [13]:
# compare the difference between list of lists and arrays
#list of lists
print(my_list[1:3]) 
#arrays
print(arr2[1:3])

[[1, 2, 3, 4], [4, 5, 6, 7]]
[[1 2 3 4]
 [4 5 6 7]]


In [14]:
#for elemen
print(my_list[2][1])
print(arr2[2,1])

5
5


In [15]:
#for different rows
new_list = [my_list[4] , my_list[0]]
print(new_list)
#for arrays use list
diff_rows = arr2[[4,0]]
print(diff_rows)

[[4, 5, 6, 7], [1, 1, 1, 1]]
[[4 5 6 7]
 [1 1 1 1]]


In [16]:
#lets practise for columns
#lists
r_1 = []
for row in my_list:
    row_1 = row[0]
    r_1.append(row_1)
print(r_1)

[1, 1, 4, 7, 4, 7]


In [17]:
#arrays
r1= arr2[:,0]
print(r1)

[1 1 4 7 4 7]


In [18]:
#multible columns lists
cols = []
for row in my_list:
    a = [row[0] , row[2] , row[3]]
    cols.append(a)
print(cols)

[[1, 1, 1], [1, 3, 4], [4, 6, 7], [7, 9, 1], [4, 6, 7], [7, 9, 1]]


In [19]:
#arrays
cols = [0 , 2 ,3]
print(arr2[:,cols])

[[1 1 1]
 [1 3 4]
 [4 6 7]
 [7 9 1]
 [4 6 7]
 [7 9 1]]


In [20]:
#arrays slicing
print(arr2[1:3 , 0:3])


[[1 2 3]
 [4 5 6]]


In [21]:
print(arr2[:])

[[1 1 1 1]
 [1 2 3 4]
 [4 5 6 7]
 [7 8 9 1]
 [4 5 6 7]
 [7 8 9 1]]


In [22]:
print(arr2[:,2:4])

[[1 1]
 [3 4]
 [6 7]
 [9 1]
 [6 7]
 [9 1]]


In [23]:
print(arr2[1:4,3])

[4 7 1]


In [24]:
print(arr2[1,3])

4


In [25]:
print(arr2[:,[1,0]])

[[1 1]
 [2 1]
 [5 4]
 [8 7]
 [5 4]
 [8 7]]


#### numpy methods

In [26]:
print(arr2.sum()) # su of all elements

108


In [27]:
print(arr2.mean()) #the average

4.5


In [28]:
print(arr2.min()) #minimume value 

1


In [29]:
print(arr2.max()) #maximum value

9


In [30]:
#the minimum or maximum for each row or each column for rows axis = 1 ,for columns axis = 0
print(arr2.min(axis = 0)) #for columns

[1 1 1 1]


In [31]:
print(arr2.max(axis = 1)) #for rows

[1 4 7 9 7 9]


### arithmatic operations on vectors

In [32]:
col1 = arr2[:,0]
col2 = arr2[:,1]
print(col1 , col2)

[1 1 4 7 4 7] [1 2 5 8 5 8]


In [33]:
print(col1 * col2)

[ 1  2 20 56 20 56]


In [34]:
print(col1 + col2)

[ 2  3  9 15  9 15]


In [35]:
print(col1 / col2)

[1.    0.5   0.8   0.875 0.8   0.875]


In [36]:
print(col1 - col2)

[ 0 -1 -1 -1 -1 -1]


In [37]:
print(col1 / 2)

[0.5 0.5 2.  3.5 2.  3.5]


In [38]:
print(col2 * 3)

[ 3  6 15 24 15 24]


In [39]:
print(np.linspace(1,3,6))

[1.  1.4 1.8 2.2 2.6 3. ]


### working on the NYC taxi dataset

In [40]:
import csv 
f = open("nyc_taxis.csv")
taxi_list = list(csv.reader(f))
header= taxi_list[0]


In [41]:
converted_data = []
for row in taxi_list[1:]:
    converted_row = []
    for item in row:
        converted_row.append(float(item))
    converted_data.append(converted_row)

In [42]:
# convert the data to array
taxi = np.array(converted_data)
print(taxi[0])
taxi.shape

[2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 4.000e+00
 2.100e+01 2.037e+03 5.200e+01 8.000e-01 5.540e+00 1.165e+01 6.999e+01
 1.000e+00]


(89560, 15)

### slicing in numpy and the difference between list of lists

In [43]:
# select a single row
first_row = taxi[0]
print(first_row)

[2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 4.000e+00
 2.100e+01 2.037e+03 5.200e+01 8.000e-01 5.540e+00 1.165e+01 6.999e+01
 1.000e+00]


In [44]:
# select multible rows
multible_rows = taxi[20:25]

# specific item 
item = taxi[10 ,9]
print(item)

52.0


In [45]:
#selecting column 
c1 = taxi[:, 0]
print("c1 is",c1)

c1 is [2016. 2016. 2016. ... 2016. 2016. 2016.]


In [46]:
#selecting columns
taxi[:, 1:4]

array([[ 1.,  1.,  5.],
       [ 1.,  1.,  5.],
       [ 1.,  1.,  5.],
       ...,
       [ 6., 30.,  4.],
       [ 6., 30.,  4.],
       [ 6., 30.,  4.]])

In [47]:
#selecting multiple columns

cols = [1,5,7]
those_cols = taxi[:, cols]
print(those_cols) #retuens 2D ndarray

[[ 1.    2.   21.  ]
 [ 1.    2.   16.29]
 [ 1.    2.   12.7 ]
 ...
 [ 6.    2.   17.48]
 [ 6.    2.   12.76]
 [ 6.    2.   17.54]]


In [48]:
#select 2D slice
taxi[1:3 , 1:5]

array([[1., 1., 5., 0.],
       [1., 1., 5., 0.]])

In [49]:
# vector math or math operations on arrays
# add some columns
sums = taxi[:, 1] + taxi[:, 2]
print(sums)
mul = taxi[:, 1:3] * taxi[:,3:4]
mul

[ 2.  2.  2. ... 36. 36. 36.]


array([[  5.,   5.],
       [  5.,   5.],
       [  5.,   5.],
       ...,
       [ 24., 120.],
       [ 24., 120.],
       [ 24., 120.]])

In [50]:
mul2 = taxi[:,1:3] * 5
print(mul2.shape)
mul2.sum()

(89560, 2)


8646125.0

In [51]:
#calculations for 2D ndarray

taxi[1:550 , 2:8].sum()

15871.47

In [52]:
# for each column 
taxi.min(axis = 0)

array([ 2.016e+03,  1.000e+00,  1.000e+00,  1.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  1.000e+00, -5.200e+01,
       -1.800e+00, -5.540e+00,  0.000e+00, -5.834e+01,  1.000e+00])

In [53]:
#for each row 
taxi.max(axis = 1)

array([2037., 2016., 2016., ..., 2822., 2016., 2016.])

In [54]:
x= np.array([1,2,1])
b = x == 1
x[b]

array([1, 1])