# 100 numpy exercises

- import numpy package as np

In [2]:
import numpy as np

- print the numpy version and configration

- create null vectorof size 10

In [3]:
vector = np.zeros(10)
vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

- how to find the memory size of any array 

In [4]:
# answe: multiply the element size * number of elements
vector.itemsize * vector.size

80

- how to get the documentation of numpy add function from the command line?

- Create a null vector of size 10 but the fifth value which is 1 

In [6]:
arr = np.zeros(10)
arr[4] = 5
print(arr)

[0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]


- Create a vector with values ranging from 10 to 49 

In [8]:
v2 = np.arange(10,50)
v2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

- Reverse a vector (first element becomes last)

array([], dtype=int32)

- Create a 3x3 matrix with values ranging from 0 to 8

array([0, 1, 2, 3, 4, 5, 6, 7])

-  Find indices of non-zero elements from [1,2,0,0,4,0]

In [16]:
v = np.array([1,2,0,0,4,0])
v[v != 0]

array([1, 2, 4])

- Create a 3x3 identity matrix 

In [18]:
np.array([[1,1,1],[1,1,1],[1,1,1]])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

##### 8. Reverse a vector (first element becomes last)

In [39]:
arr = np.array([1,2,0,0,4,0])
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)